### PR TITLE
Fix directory contexts

### PR DESCRIPTION
**Pull request by Aeilert**
Make sure directory arguments (from pipeline) are correctly parsed inside cache functions.

Solves #69.

### CODE REVIEW

**Comment by Aeilert** [comment]
Hi @randrescastaneda, 

Could you take some time to review this briefly. No major changes here, but I think it is important for the pipeline that directory parameters are being passed down to within the pipdm functions. I thus substituted some `getOption("pip.maindir")` with `pip_data_dir` etc. Could you have a look and see if make sense. 

Thanks. 

/Aleksander

**Comment by randrescastaneda** [comment]
HI @Aeilert , 

I think it is technically ok, but I still don't understand the rational. I think you're right, but could you please expand on why this way is better than the previous one?

Thanks. 
Best,

**Comment by Aeilert** [comment]
Hi @randrescastaneda ,

Sure. The issue with the current code is that the directories are only read from the zzz.R options in `{pipdm}` and `{pipload}`, and not overwritten with the directory settings supplied by the user (e.g. in `_targets.R` ). That runs the risk of the pipeline implicitly loading the datasets (PFW, Inventory) from different locations.

Hope that was more clarifying. 

/Aleksander

**Comment by randrescastaneda** [comment]
Super clear now. Thank you.

**Pull request merged**
